"""
================================================================================
DAY 3 - BLOCK 4: GROUNDEDNESS, HALLUCINATION, RAGAS, AND EVAL METRICS
================================================================================
Goal:
Understand how to evaluate RAG and agentic AI systems using metrics such as
faithfulness, groundedness, answer relevancy, context precision, context recall,
tool-calling correctness, classification precision/recall, and hallucination
rate.

Why this matters for the DTDL JD:
The JD mentions GenAI platform testing, eval workflows, analytics dashboards,
synthetic traces, prompt/tool/SOP authoring, and catching silent quality bugs.
This block is the core answer to:

    "How will you test an AI workbench?"

================================================================================
"""


# =============================================================================
# CONCEPT 1: WHY AI EVALUATION IS DIFFERENT FROM NORMAL TESTING
# =============================================================================
"""
Traditional functional test:

    input -> exact expected output

Example:
    2 + 2 -> 4

LLM/RAG/agent test:

    input -> retrieved context/tool call/intermediate steps/final answer

The answer may be worded differently each time, so exact string matching is weak.
Instead, we evaluate dimensions of quality:

    - Is the answer grounded in retrieved context or tool result?
    - Is the answer relevant to the user question?
    - Did retrieval fetch the right chunks?
    - Did the model invent unsupported facts?
    - Did the agent choose the correct tool?
    - Did it avoid unsafe or restricted behavior?
    - Did it stay within latency/cost limits?

Senior SDET point:
    AI testing is not only "did output equal expected text?"
    It is "did the system follow the right evidence, path, and quality contract?"
"""


# =============================================================================
# CONCEPT 2: BASIC DATA SHAPE FOR RAG EVALUATION
# =============================================================================
"""
A typical RAG eval row contains:

    question:
        User query.

    retrieved_contexts:
        Chunks retrieved by the retriever.

    response:
        Final answer generated by the model.

    reference / ground_truth:
        Expected answer or expected facts.

Example:

    question:
        "What is the refund policy?"

    retrieved_contexts:
        ["Refunds are processed within 7 business days."]

    response:
        "Refunds are processed within 7 business days."

    reference:
        "Refunds are processed within 7 business days."

For agents, we add trace fields:

    expected_tool
    actual_tool
    expected_args
    actual_args
    tool_result
    final_answer
    trace_path
"""


# =============================================================================
# CONCEPT 3: CONFUSION MATRIX BASICS
# =============================================================================
"""
Confusion matrix is used when the evaluation is classification-like.

Examples:

    - intent classification:
        expected intent vs actual intent

    - safety classification:
        unsafe vs safe

    - hallucination detection:
        hallucinated vs not hallucinated

    - tool selection:
        expected tool vs actual tool


Binary confusion matrix:

                    Predicted Positive    Predicted Negative
    Actual Positive        TP                    FN
    Actual Negative        FP                    TN

Definitions:

    TP = True Positive
        System correctly predicted the positive class.

    FP = False Positive
        System predicted positive, but actual was negative.

    FN = False Negative
        System predicted negative, but actual was positive.

    TN = True Negative
        System correctly predicted the negative class.


Safety example:

    Positive class = unsafe request

    TP:
        Unsafe prompt correctly blocked.

    FP:
        Safe prompt incorrectly blocked.
        Example from Block 2:
            "Hello, how are you?" classified as blocked.

    FN:
        Unsafe prompt not blocked.
        This is usually more dangerous than FP.

    TN:
        Safe prompt allowed.
"""


# =============================================================================
# CONCEPT 4: CLASSIFICATION METRICS AND FORMULAS
# =============================================================================
"""
Accuracy:

    Formula:
        accuracy = (TP + TN) / (TP + FP + FN + TN)

    Meaning:
        Out of all predictions, how many were correct?

    Limitation:
        Can be misleading when classes are imbalanced.


Precision:

    Formula:
        precision = TP / (TP + FP)

    Meaning:
        When the system predicts positive, how often is it correct?

    Safety example:
        When the model blocks a prompt, how often was the prompt truly unsafe?

    Low precision means:
        Too many false positives / over-blocking.


Recall:

    Formula:
        recall = TP / (TP + FN)

    Meaning:
        Out of all actual positive cases, how many did the system catch?

    Safety example:
        Out of all unsafe prompts, how many were blocked?

    Low recall means:
        Too many false negatives / unsafe prompts bypassing guardrail.


F1 Score:

    Formula:
        F1 = 2 * (precision * recall) / (precision + recall)

    Meaning:
        Harmonic mean of precision and recall.

    Use when:
        You need one balanced metric.


False Positive Rate:

    Formula:
        FPR = FP / (FP + TN)

    Meaning:
        Out of all actual negative/safe cases, how many were incorrectly flagged?


False Negative Rate:

    Formula:
        FNR = FN / (FN + TP)

    Meaning:
        Out of all actual positive/unsafe cases, how many were missed?


Interview point:
    For safety/guardrails, recall is very important because missed unsafe prompts
    are high risk. But precision also matters because excessive over-blocking
    hurts user experience.
"""


# =============================================================================
# CONCEPT 5: RETRIEVAL METRICS
# =============================================================================
"""
Retrieval metrics evaluate whether the retriever fetched the right context before
the LLM generated the answer.

The most common issue:
    The LLM may answer badly because retrieval was bad, not because the model was
    bad.


Context Precision:

    Question:
        "Of the chunks retrieved, how many were actually relevant?"

    Simple formula:
        context_precision = relevant_retrieved_chunks / total_retrieved_chunks

    Example:
        Retrieved 4 chunks.
        3 were relevant.

        context_precision = 3 / 4 = 0.75

    Low context precision means:
        Retriever is bringing noisy/irrelevant chunks.

    Impact:
        LLM may get distracted and produce wrong or mixed answers.


Context Recall:

    Question:
        "Of all required/ground-truth information, how much did retrieval find?"

    Simple formula:
        context_recall = relevant_retrieved_ground_truth_chunks / total_required_ground_truth_chunks

    Example:
        Ground truth needs 3 facts.
        Retrieved context contains 2 facts.

        context_recall = 2 / 3 = 0.67

    Low context recall means:
        Retriever missed important information.

    Impact:
        LLM may hallucinate to fill missing gaps.


Retriever Precision@K:

    Formula:
        precision@k = relevant_docs_in_top_k / k

    Example:
        Top 5 retrieved docs contain 3 relevant docs.

        precision@5 = 3 / 5 = 0.60


Retriever Recall@K:

    Formula:
        recall@k = relevant_docs_in_top_k / total_relevant_docs

    Example:
        There are 4 known relevant docs.
        Top 5 retrieved docs contain 3 of them.

        recall@5 = 3 / 4 = 0.75


Mean Reciprocal Rank (MRR):

    Formula:
        reciprocal_rank = 1 / rank_of_first_relevant_result
        MRR = average reciprocal_rank across all queries

    Example:
        First relevant result appears at rank 2.

        reciprocal_rank = 1 / 2 = 0.5

    Meaning:
        Measures how early the first useful result appears.


Interview point:
    If context precision is low, I inspect noisy chunks and retrieval ranking.
    If context recall is low, I inspect chunking, embeddings, filters, and top_k.
"""


# =============================================================================
# CONCEPT 6: GENERATION METRICS
# =============================================================================
"""
Generation metrics evaluate the final answer after retrieval/tool execution.


Faithfulness:

    Question:
        "Is the answer supported by the retrieved context?"

    RAGAS-style idea:
        Break answer into claims.
        Check whether each claim can be inferred from context.

    Conceptual formula:
        faithfulness = supported_answer_claims / total_answer_claims

    Example:
        Answer has 4 factual claims.
        Context supports 3.

        faithfulness = 3 / 4 = 0.75

    Low faithfulness means:
        Answer contains unsupported claims.

    Strong signal of:
        hallucination.


Groundedness:

    Question:
        "Is the answer grounded in the provided evidence?"

    Very similar to faithfulness.
    In many tools, groundedness and faithfulness are used closely.

    Difference in wording:
        faithfulness often refers to consistency with retrieved context.
        groundedness often refers to being backed by source evidence/tool output.

    For agents:
        Final answer should be grounded in tool_result.

    Example:
        Tool result says:
            customer status = inactive

        Final answer says:
            customer is active

        This is not grounded.


Answer Relevancy:

    Question:
        "Does the answer address the user's question?"

    Conceptual formula:
        answer_relevancy = semantic_similarity(question, answer)

    Or RAGAS-style:
        Generate possible questions from answer.
        Compare generated questions to original question.

    Low answer relevancy means:
        The answer may be true but off-topic.

    Example:
        User asks:
            "What is refund policy?"

        Answer:
            "You can reset password in Settings."

        Faithfulness may be high if context supports it, but relevancy is low.


Answer Correctness:

    Question:
        "Is the answer correct compared to reference/ground truth?"

    Conceptual formula:
        answer_correctness = similarity(response, reference) plus factual overlap

    Use when:
        You have a reference answer.


Semantic Similarity:

    Formula idea:
        similarity = cosine_similarity(embedding(answer), embedding(reference))

    Cosine similarity:
        cosine(A, B) = dot(A, B) / (||A|| * ||B||)

    Meaning:
        Measures whether two texts are close in meaning.

    Limitation:
        High semantic similarity does not always prove factual correctness.
"""


# =============================================================================
# CONCEPT 7: HALLUCINATION METRICS
# =============================================================================
"""
Hallucination:

    The model produces information not supported by context, tool output, or
    known ground truth.


Hallucination Rate:

    Formula:
        hallucination_rate = hallucinated_answers / total_answers

    Example:
        20 answers evaluated.
        3 contain unsupported facts.

        hallucination_rate = 3 / 20 = 0.15


Unsupported Claim Rate:

    Formula:
        unsupported_claim_rate = unsupported_claims / total_claims

    Example:
        Across all answers, there are 100 claims.
        12 are unsupported.

        unsupported_claim_rate = 12 / 100 = 0.12


For RAG:
    Hallucination often comes from:

        - missing context
        - irrelevant context
        - outdated context
        - prompt asks model to infer beyond evidence
        - model ignores context


For agents:
    Hallucination often comes from:

        - tool failed but final answer claims success
        - tool returned one value but final answer changes it
        - model invents ticket/customer/order data
        - model skips tool and answers from memory


Block 3 example:

    Input:
        "Find customer CUST-999"

    Tool result:
        success=False, error="Customer not found"

    Bad final answer:
        "Customer CUST-999 is Rahul with Premium plan."

    This is hallucination because the answer invents customer details.
"""


# =============================================================================
# CONCEPT 8: TOOL AND AGENT METRICS
# =============================================================================
"""
Tool Selection Accuracy:

    Formula:
        tool_selection_accuracy = correct_tool_selections / total_tool_selection_cases

    Example:
        50 tool-needed prompts.
        Model selected correct tool 45 times.

        tool_selection_accuracy = 45 / 50 = 0.90


Tool Argument Accuracy:

    Formula:
        argument_accuracy = correct_argument_sets / total_tool_calls

    Example:
        Expected:
            {"customer_id": "CUST-101"}

        Actual:
            {"customer_id": "CUST-10"}

        Incorrect.


Per-field Argument Accuracy:

    Formula:
        field_accuracy = correct_fields / total_expected_fields

    Example:
        Expected:
            {"title": "Checkout Failure", "priority": "high"}

        Actual:
            {"title": "Checkout Failure", "priority": "medium"}

        correct_fields = 1
        total_expected_fields = 2

        field_accuracy = 1 / 2 = 0.50


Agent Trajectory Accuracy:

    Formula:
        trajectory_accuracy = correct_trajectories / total_agent_runs

    Example expected path:
        ["classifier", "tool_call", "final_response"]

    Actual path:
        ["classifier", "direct_answer", "final_response"]

    Incorrect trajectory.


Tool Grounding Score:

    Question:
        "Did final answer accurately reflect tool result?"

    Simple scoring:
        1 = fully grounded
        0 = not grounded

    Formula:
        tool_grounding_rate = grounded_tool_answers / total_tool_answers


Tool Error Handling Rate:

    Formula:
        tool_error_handling_rate = correctly_handled_tool_errors / total_tool_error_cases

    Example:
        Tool fails 10 times.
        Agent explains failure 8 times and hallucinates success 2 times.

        tool_error_handling_rate = 8 / 10 = 0.80
"""


# =============================================================================
# CONCEPT 9: DASHBOARD INTERPRETATION
# =============================================================================
"""
When reading a RAG/agent evaluation dashboard, do not only look at one metric.
Look at combinations.


Case 1:
    context_precision low
    context_recall high
    faithfulness low

Meaning:
    Retriever finds some required info but also brings noisy chunks.
    Model may be distracted by irrelevant context.

Likely fixes:
    improve ranking, metadata filters, chunk quality, reranker.


Case 2:
    context_precision high
    context_recall low
    faithfulness low

Meaning:
    Retrieved chunks are relevant, but important facts are missing.
    Model may hallucinate because context is incomplete.

Likely fixes:
    increase top_k, improve chunk overlap, improve embeddings, add missing docs.


Case 3:
    context_precision high
    context_recall high
    faithfulness low

Meaning:
    Retrieval is good, but generation is bad.
    Model is not following evidence.

Likely fixes:
    prompt changes, stronger instruction to answer only from context, better
    model, citation requirement.


Case 4:
    faithfulness high
    answer_relevancy low

Meaning:
    Answer is grounded but does not answer the actual question.

Likely fixes:
    query rewriting, prompt improvement, better intent understanding.


Case 5:
    tool_selection_accuracy high
    argument_accuracy low

Meaning:
    Model knows which tool to call but extracts wrong fields.

Likely fixes:
    better tool descriptions, examples in prompt, stricter schema, enum fields.


Case 6:
    tool execution success high
    final answer grounding low

Meaning:
    Tools work, but model misreports results.

Likely fixes:
    final response prompt, structured final answer, tool result citation.
"""


# =============================================================================
# CONCEPT 10: PYTEST GATES FOR METRICS
# =============================================================================
"""
Your existing project already has this pattern:

    testing-framework/tests/helpers/ragas_assertions.py

Concept:

    evaluate dataset with metric
    convert results to pandas
    assert score >= threshold

Example threshold gates:

    faithfulness >= 0.70
    answer_relevancy >= 0.75
    context_precision >= 0.60
    context_recall >= 0.60


Simple pytest pattern:

    def test_faithfulness_above_threshold(eval_df):
        assert eval_df["faithfulness"].mean() >= 0.70


Better pytest pattern:

    def test_each_answer_faithfulness_above_threshold(eval_df):
        failing = eval_df[eval_df["faithfulness"] < 0.70]
        assert failing.empty, failing[["question", "response", "faithfulness"]]


Why per-row checks are better:
    Average can hide bad individual failures.

Example:
    9 answers score 1.0
    1 answer scores 0.0
    average = 0.90

The average looks good, but one user got a fully hallucinated answer.
"""


# =============================================================================
# CONCEPT 11: SMALL MANUAL FORMULA EXAMPLE
# =============================================================================
"""
Suppose we evaluate 10 safety prompts.

Actual unsafe prompts:
    4

Actual safe prompts:
    6

Model blocked:
    5 prompts

Breakdown:
    TP = 3  unsafe correctly blocked
    FP = 2  safe incorrectly blocked
    FN = 1  unsafe missed
    TN = 4  safe allowed

Accuracy:
    (TP + TN) / total = (3 + 4) / 10 = 0.70

Precision:
    TP / (TP + FP) = 3 / (3 + 2) = 0.60

Recall:
    TP / (TP + FN) = 3 / (3 + 1) = 0.75

F1:
    2 * (0.60 * 0.75) / (0.60 + 0.75)
    = 0.67

False positive rate:
    FP / (FP + TN) = 2 / (2 + 4) = 0.33

False negative rate:
    FN / (FN + TP) = 1 / (1 + 3) = 0.25

Interpretation:
    Recall is decent, but precision is low. The system blocks too many safe
    prompts. This is the over-blocking issue you saw in Block 2.
"""


# =============================================================================
# CONCEPT 12: PRACTICE TASKS
# =============================================================================
"""
In the Block 4 notebook, write code yourself for:

1. Create a small pandas DataFrame with:
       question, response, reference, context_precision, context_recall,
       faithfulness, answer_relevancy

2. Calculate:
       mean faithfulness
       mean answer relevancy
       rows below threshold

3. Create a small confusion matrix for guardrail classification:
       expected_label, actual_label

4. Calculate:
       TP, FP, FN, TN
       accuracy
       precision
       recall
       F1

5. Create a mini tool-calling eval DataFrame:
       expected_tool, actual_tool, expected_args, actual_args

6. Calculate:
       tool selection accuracy
       argument accuracy

Then we will convert selected checks into:

    tests/test_groundedness.py
"""


# =============================================================================
# CHECKPOINT QUESTIONS
# =============================================================================
"""
1. What is the difference between faithfulness and answer relevancy?

Faithfulness checks whether the answer is supported by the retrieved context or
tool result. Answer relevancy checks whether the answer addresses the user's
question. An answer can be faithful but irrelevant if it is grounded in context
but answers the wrong thing.


2. What does low context recall mean?

Low context recall means retrieval missed important information required to
answer the question. This often causes hallucination because the model may fill
missing gaps from its own knowledge.


3. What does low context precision mean?

Low context precision means the retriever returned noisy or irrelevant chunks.
This can distract the model and lead to mixed, incorrect, or irrelevant answers.


4. How do you detect hallucination after a tool failure?

Check whether the final answer is grounded in the tool result. If the tool
returns success=False or "Customer not found", the final answer must not invent
customer details, ticket ids, prices, statuses, or calculations.


5. How would you explain this block in an interview?

Interview answer:

    "For AI evaluation, I split quality into retrieval, generation, tool, and
    safety metrics. For retrieval, I track context precision and context recall.
    For generation, I track faithfulness, groundedness, answer relevancy, and
    hallucination rate. For agents, I add tool selection accuracy, argument
    accuracy, trajectory accuracy, and tool-result grounding. I use dashboards to
    diagnose whether a failure came from retrieval, model generation, tool
    execution, or guardrails, and I convert stable thresholds into pytest gates."
"""
